### ISSUE TITLE
2.8x update

### ISSUE THREAD

**Issue by p2or** [p2or/blender-loom#1]
- Module Registration 
 - Class Registration (Naming, Access)
 - Display Enum (*Render Image Sequence*)?
 ...

**Comment by AndreaMonzini** [comment]
Hello, great add-on !
Could be compatible with EEVEE and OpenGL render in 2.8?
Is there a way to manage subframes sequence to animate the slow motion speed ?
Thank you.

**Comment by p2or** [comment]
Hi Andrea,

glad you like it. Yep, I hope we can make all that work. However, since the python API for 2.8 isn't finished yet, I think we would wasting time trying to implement that right now. Anyway, if you have any suggestions please let me know.

> Is there a way to manage subframes sequence to animate the slow motion speed change?

Definitely *Off-Topic* here, please open up a new issue for that, ideally along with any reasonable example to keep things organized. Thanks.

Cheers,
Christian

**Comment by StrobFX** [comment]
Hi, ios it working in 2.8 with Eevee now?

**Comment by p2or** [comment]
Hey guys,

good news, I got all working so far and added a new *pre-release* version for *2.8x*. In case you encounter any issues, just let me know. Closing for now.

Cheers,
Christian
