### ISSUE TITLE
"Render Selected Keyframes" functionality doesn't work with Grease Pencil Keyframes - Blender 4.3.1 - Loom 0.9.3

### ISSUE THREAD

**Issue by Mickeymoustique** [p2or/blender-loom#103]
Hello, I found an error using the great Loom addon :)

Thank you for your work.

**Blender Version**
Broken: version: 4.3.1, branch: blender-v4.3-release, commit date: 2024-12-10 07:46, hash: `33d812126174`
Worked: 4.2.4

**Loom Version**
0.9.3

**Short description of error**
"Render Selected Keyframes" functionality doesn't work with Grease Pencil Keyframes. When GP keyframes are selected and the button "Render Selected Keyframes" is pressed an error appears saying "No Keyframes Selected".

Hint here : The new Grease Pencil V3 may be the source of the problem because the "Render Selected Keyframes" functionality works fine outside Grease Pencil in Blender 4.3.1 AND also works fine with Grease Pencil V2 in Blender 4.2.4

**Exact steps to reproduce the error**
- Create a new default 2D animation file
- Draw some things at differents frames
- Select some keyframes you've just created
- In the dope sheet timeline, select grease pencil mode
- Press "Render Selected Keyframes" in the top right of the grease pencil timeline
- An error appears saying "No Keyframes Selected"

![Print_1](https://github.com/user-attachments/assets/afcc995c-e540-4931-beff-ce1dc4388f79)

![Print_2](https://github.com/user-attachments/assets/9059485e-bffd-40de-9ede-4b4ab7dd2e13)

**Comment by p2or** [comment]
Hi @Mickeymoustique,

thanks for your detailed report. Indeed, the [API has beed changed](https://developer.blender.org/docs/release_notes/4.3/grease_pencil_migration/#python-api) as of Blender 4.3. This behavior should be fixed as of my [latest commit](https://github.com/p2or/blender-loom/commit/8b3ba4aa9db942722d620e8ca960397054d5c0b7) though. If you have the time, please clone or download _Loom_ from the [master branch](https://github.com/p2or/blender-loom) and report back. Can you confirm?

Cheers,
Christian

**Comment by Mickeymoustique** [comment]
Hi Christian,

First of all, thank you very much for your responsiveness and quick reply ! That's just amazing ! :) 
I have downloaded and tested the master branch, and I can confirm that the functionality now works perfectly with Grease Pencil. Thanks again !

Cheers,
Mickey (not Mouse though..)

**Comment by p2or** [comment]
Hi Mickey,

thank you for your feedback. No problem, glad I could help. Closing for now...

Cheers,
Christian
