### ISSUE TITLE
No filling options when missing frames detected

### ISSUE THREAD

**Issue by L0Lock** [p2or/blender-loom#12]
The docs says:

>  - You can **verify the image sequence** on disk before encoding by clicking the *Verify Image Sequence* operator ![I1](https://i.stack.imgur.com/JovW0.jpg), which also detects all frames missing frames of the sequence
>  - In case there are **missing frames**, the addon either provides an utility function to fill the gaps of the image sequence with copies of the nearest frame to get the full lenght animation and another operator to render all missing frames:
>  
>    ![Encode Image Sequence Dialog](https://i.stack.imgur.com/ul9ld.jpg)

I'm very interested in this feature, as combined with the render from selected keyframes it allows a big speed up in any 2D-ish animation.

Though in my case, it doesn't seem to work. I hit the ghost icon as suggested, which does this:

![image](https://user-images.githubusercontent.com/16049822/99988709-20a45000-2db2-11eb-91f2-6e41281c8be0.png)

But nothing else happens, I don't see the buttons as in the docs.

**Comment by p2or** [comment]
Hi @L0Lock,

good catch! Simply forgot to replace the ghost icon when updating the add-on for 2.8x. If you have the time, please test the fix and report back whether the patch works. Thanks.

Cheers,
Christian

**Comment by L0Lock** [comment]
Yay, it's working!

![image](https://user-images.githubusercontent.com/16049822/100080145-c523a200-2e45-11eb-83dd-7e6f2b7ac31b.png)

Thanks for your work!

**Comment by p2or** [comment]
Ez, thanks for your report.
