### ISSUE TITLE
Render Keyframes From Dopesheet

### ISSUE THREAD

**Issue by PBnFlash** [p2or/blender-loom#23]
I cannot for the life of me work out how to just render keyframes. 

I know I tested this program and got it to work at some point in the past so I'm sure it's something I'm missing this time. 

But the "f3" to add just the keyframes doesn't seem to work. I seem to remember a menu option when I'd search loom from the dopesheet but I just can't bring it up.

**Comment by p2or** [comment]
Hi @PBnFlash,

as of version 0.8.x there is a new popover in the header of the timeline (hadn't the time to document it yet):

<img width="967" alt="Screenshot 2021-11-11 at 08 32 16" src="https://user-images.githubusercontent.com/512368/141257441-71335b26-1fd5-405e-aedc-1eb9ec8392fe.png">

<kbd>F3</kbd> is working for me as well:

<img width="695" alt="Screenshot 2021-11-11 at 08 33 28" src="https://user-images.githubusercontent.com/512368/141257517-09581b23-3928-430e-9029-4ea0d8f62021.png">
 
Cheers,
Christian

**Comment by PBnFlash** [comment]
Thanks, works great!

**Comment by PBnFlash** [comment]
It does seem to render selected object's keyframes, not just selected keyframes. 
Not an issue for me but unclear in the documentation.
