### ISSUE TITLE
Blender 3.0.0 - TOPBAR_MT_app registration error

### ISSUE THREAD

**Issue by Gattung** [p2or/blender-loom#24]
Hey just wanted to let you know loom won't install in Blender 3.0 beta or 3.1 Alpha because of the error: 

> AttributeError: 'module' object has no attribute 'TOPBAR_MT_app'

This may have some relevant info: https://www.mail-archive.com/bf-blender-cvs@blender.org/msg150277.html 

Thanks!

**Comment by Gattung** [comment]
This may have some relevant info

[https://www.mail-archive.com/bf-blender-cvs@blender.org/msg150277.html](https://www.mail-archive.com/bf-blender-cvs@blender.org/msg150277.html)

**Comment by p2or** [comment]
Hi @Gattung,

thanks for your report and the research. Just added an additional check to support versions above 3.0.0 as well. If you have the time, please test the [latest release](https://github.com/p2or/blender-loom/releases) and report back. As far as I can tell, all is working as expected using 2.9x and 3.0.0 Beta now.

Cheers,
Christian

**Comment by Gattung** [comment]
Working in Blender 3, thanks!
