### ISSUE TITLE
Render Image Sequence with new Date Created verses Date Modified

### ISSUE THREAD

**Issue by lilyfurn** [p2or/blender-loom#26]
Great tool! Is there is a way to set overwrite "Date created" when saving the image sequence. The logic makes perfect sense changing the "Date modified" time stamp with each render, but what do I do if I want fresh "Date created" timestamp for the files without creating a new directory for the sequence output? does this result from windows log or can I set this in loom.py/blender? 

Thanks

![image](https://user-images.githubusercontent.com/98041264/150167632-63bb71b3-114c-48d8-bead-8db1d0eddfaf.png)

**Comment by p2or** [comment]
Hi @lilyfurn,

how the image is stored is fully controlled by Blender, Loom basically just manages the rendering of each frame. I'm afraid I can't help here (if there is no serious reason for it). However, I'm sure that there are tools allowing to batch modify the creation date (OS dependent), eg. just a few lines in python: https://stackoverflow.com/questions/11348953/how-can-i-set-the-last-modified-time-of-a-file-from-python

Hope this helps anyway, Cheers!
Christian

**Comment by lilyfurn** [comment]
Any feedback is helpful for sure! Thanks for response. Cheers!
