### ISSUE TITLE
Pose library actions will be added as keyframes by default

### ISSUE THREAD

**Issue by prof-kerfuffle** [p2or/blender-loom#27]
Hey, great library, my only gripe is that if you're working with a rig that has a pose library, and you choose 'Render selected keyframes' those poses will be added as keyframes, as the pose lib is just an action strip. 

So if I have anim with keyframes on frames 0 and 10, and a few poses in the pose lib, it'll output 0,1,2,3.. and 10 as the selected range, since all_selected_ctrl_points  () seems to look through all actions of the object.

As I looked through the code, I noticed one can Alt click the option to trigger the selected_ctrl_points function instead of the all_selected_ctrl_points function, but I couldn't find this in the instructions, perhaps I missed it, but I think it might be a good idea for this to be either the default or an explicit option, since I'm guessing using the pose lib is quite common.

Thanks for the great addon!

Versions tested: 2.93, 3.0, addon version 0.8.3

**Comment by p2or** [comment]
Hi @prof-kerfuffle,

many thanks for your feedback. Yeah, you're right...

As of the latest commit (73ab4d0f3a881a484e333172616b19cd1358ade3), the logic is now inverted - getting the keyframes from all objects in selection is the new default and there is a property now to get all selected keyframes from all other objects in the scene, if desired: 

<img width="261" alt="Screenshot 2022-02-16 at 06 20 57" src="https://user-images.githubusercontent.com/512368/154202494-8397de2e-eeae-4a3a-9a5c-2c5c96242236.png">

What do you think? If you have the time, please test the changes and report back whether that works. And please excuse the bad documentation, I had no time in the last months to take care. If you have some time to improve the documentation, I would appreciate any contribution, especially from someone like you who also understands the code ;)

Cheers,
Christian

**Comment by Hammers69** [comment]
Hi @p2or,
Still very much exploring and experimenting, so could be user error again, but just thought I'd chime in on this issue. I have a very basic layout scene atm, but with lots of linked assets. If I don't have the 'scene keyframes' selected, the correct keys are extracted (for the selected object), but with all my keyframed assets selected in the dopesheet and 'scene keyframes' selected, I'm getting the correct keys within the scene frame range, but also a ton of keys outside the range, even though there are no other keyframes in this master scene. I guess they're getting pulled from the linked libraries but not sure.

It seems like limiting the output frames to the actual render frame range  would make sense, but I'm not sure what the core issue is.

example keys (no others in the file):
![Screen Shot 2022-10-03 at 12 01 46 pm](https://user-images.githubusercontent.com/38600234/193488993-ec193241-b14a-4e1c-9f44-28388473b4ec.png)

desired output - without 'scene keyframes' and 'Tromboner' selected:
![Screen Shot 2022-10-03 at 12 06 10 pm](https://user-images.githubusercontent.com/38600234/193489335-1c66ee33-9464-4d80-a76f-f320f402bf07.png)

result with 'scene keyframes' on:
![Screen Shot 2022-10-03 at 12 04 08 pm](https://user-images.githubusercontent.com/38600234/193489163-e2cc93b2-0a92-463c-861b-d6a0417872d8.png)

`-4,-2-6,8-10,13-76,79-96,98-105,107-116,120-135,185-192,196,202,204-207,209-242,250,548,561,577,590,602,1810,1826,1836-1837,1839-1840,1842,1844,1847,1849-1850,1853,1855,1857,1859-1860,1862,1864,1866,1868-1869,1871,1873,1875,1878,1880,1883,1885,1887-1888,1891,1893,1895,1897-1898,1900,1902,1904,1906-1907,1909,1912,1914,1916-1917,1919,1922,1924,1926-1927,1929,1931,1933,1935-1937,1939,1941,1943-1944,1946-1947,1949,1951,1953-1954,1956,1958,1960,1962-1963,1965-1966,1968,1970,1972-1973,1975,1978,1980,1982-1983,1985,1988,1990,1992-1993,1996,1998,2000,2002,2004,2006,2008`

After now going through the character rig files and removing some unneeded actions, I've got the list down a fair bit, but still an issue, so I assume the addon is finding keys in all the linked libraries, even when the action is not used directly. Hoping there's a way to limit the keys to just those within the actual scene and frame range. Let me know if you'd like any more info. Cheers!

frame list number 2:
`-4,-2-6,8-10,13-76,79-96,98-105,107-116,120-135,185-192,196,202,204-207,209-242,250,548,561,577,590,602`

**Comment by Hammers69** [comment]
Thanks @p2or ! The scene frame range would be great to implement if you can. I'm working on a big fairly complex project now, and your addon is an awesome help for more stop-motion styles.

I'll try to put together something to help illustrate the variables and I'll post a new issue here when I've got it together. Thanks so much
