### ISSUE TITLE
Temporary UI corruption

### ISSUE THREAD

**Issue by Gattung** [p2or/blender-loom#28]
This is probably more to do with Blender but just thought I'd mention it as I don't see it with anything else.

In Blender 3.1 3.2 when using loom 'render with commandline' option my blender ui gets corrupted but if I mouse over the panels they restore to normal so it doesn't crash or anything.
<img width="1912" alt="2022-02-14" src="https://user-images.githubusercontent.com/244226/154344736-27b5f199-a4d8-4846-86ae-100fded7a5a7.png">
.

**Comment by p2or** [comment]
Hi @Gattung,

whoa, beautiful. Thanks for letting me know. I can not reproduce it using the latest Alpha build though `Blender 3.2.0 Alpha (hash b626edd751d6 built 2022-02-17 01:50:52)`. Perhaps they fixed this issue yesterday...? A trusty gif:

![ezgif-5-d1dd05c960](https://user-images.githubusercontent.com/512368/154444366-4259c78f-ee10-49e6-9ea5-092256b3481a.gif)

Also, some errors popping up in the console that the `.obj` module is missing and such, I think it's too early to put any effort into this. Closing for now, if this happens with the beta again, feel free to post it here and I'll reopen the issue.

Cheers,
Christian
