### ISSUE TITLE
'Fill gaps with copies' doesn't extend to start or end of scene frame range 

### ISSUE THREAD

**Issue by Hammers69** [p2or/blender-loom#33]
Hi p2or,
I've been doing more testing to figure out the issues I was having and whether I need to report anything. But in the meantime I thought I'd post a couple of things I've discovered. This first one I hope is a fairly simple bug fix.

As the title suggests, 'Fill gaps with copies' in the encode panel only fills frames between the min and max existing frames. It would be great, and I think expected, that the function would fill to the start and end of the scene frame range, since typically it's important to keep shot frame ranges consistent through layout, previs, to editing and final render, say. 

I've attached a basic scene file which renders on frames 2 and 8, with a scene frame range of 1-10. After rendering with 'Render Selected Keyframes' the FGwC function fills in frames 3-7, but not 1, 9 or 10.

Many thanks!
Stephen.

[FillSeqTest.zip](https://github.com/p2or/blender-loom/files/9943082/FillSeqTest.zip)

**Comment by p2or** [comment]
Hi @Hammers69,

good news, I think I got it all working. As of the [latest commit](https://github.com/p2or/blender-loom/commit/bd44f41a201ec0adb6fbf5d15d9ff8d5ffa495a9), the frame range of the scene is taken into account by default. Also when rendered using Loom the 'sequence path' will be set to properly if you click the 'Auto Paths' button.

Please download Loom from [here](https://github.com/p2or/blender-loom/tree/scene_frames) and report back. I hope this will save you some time.

Cheers,
Christian
