### ISSUE TITLE
Enhancement: Limit to scene frame range

### ISSUE THREAD

**Issue by Hammers69** [p2or/blender-loom#35]
As we discussed in our previous thread, just pulling it out for clarity--again I'm mostly looking at 'Render Selected Keyframes' for my workflow. 

It would be superb to have an option, a boolean toggle I guess to limit keyframes to within the scene frame range automatically. Accidentally rendering outside of the frame range could cause a number of issues in a larger production.

Thanks!
Stephen.

**Comment by p2or** [comment]
Hi @Hammers69,

sorry for the delay, had to finish a project. Anyway, today I finally had the time to implement your requested option to limit the selection to the frames of the scene. For now, you can hold down <kbd>Ctrl</kbd> when clicking 'Render selected Keyframes' button, which essentially compares the range of the selected keyframes to the actual scene frame range and cuts it off (had difficulties to find an icon and a suitable place, can be improved anytime).

I created a new branch to adress all the features regarding to this, https://github.com/p2or/blender-loom/tree/scene_frames If you have the time, please download the add-on from there and report back, thanks.

Cheers,
Christian
