### ISSUE TITLE
on macos: folder in which blender is, mustn't have spaces

### ISSUE THREAD

**Issue by luckychris** [p2or/blender-loom#39]
So i called my folder "Blender GN Simulation 3.5" and tried to batch render from there and i got this:

/Users/chris/Downloads/Blender3.5 GN simulation/Blender.app/Contents/MacOS/blender -b "/Users/chris/Downloads/gn_sim_collision-tut2.blend" --python-expr "import bpy;bpy.ops.render.image_sequence(frames='1-200', isolate_numbers=False,render_silent=True, digits=4)" -t 10
read -n1 -r -p "Press any key to continue..." key
exit

although i don't know what this means, but this didn't render...and i assume there are some "" missing?

**Comment by p2or** [comment]
Hi @luckychris,

thanks for your report. Could you please help me and explain in more detail what exactly you did? From what I understand: You are using the latest and greatest *Loom* version on MacOS along with Blender 3.5 (located in your 'Downloads' folder), you would like to render multiple blend files using the 'Batch Dialog' and Blender 3.5 stops immediately after the execution?

Cheers,
Christian

**Comment by p2or** [comment]
Hi @luckychris,

I can confirm your suspicion, if I understand your issue correctly: That the binary path to Blender may contain whitespaces is currently not supported on MacOS (something I have never tested either).

Anyway, I created a [new branch](https://github.com/p2or/blender-loom/tree/binary_path_whitespaces) to adress that issue and wrapped the path in [quotations](https://github.com/p2or/blender-loom/commit/8eca9266324118e6a4dbab8c15ae2fe054dda1ab). Please download the add-on from there and report back.

Thanks,
Christian

**Comment by luckychris** [comment]
Hi Christian, 

Vielen Dank, hatte leider erst jetzt Zeit es zu testen. Läuft! Vielen lieben Dank für den schnellen Bugfix!!

Lieben Gruss
Christoph
