### ISSUE TITLE
Fill Image Sequence Gap Different Option

### ISSUE THREAD

**Issue by AlfyAnahuac** [p2or/blender-loom#42]
Hi! Thank you for this add-on it's helping me quite a bit. I noticed in the documentation it says you can fill the gaps in the image sequence by pulling the closest frame available. Is there a way to change it so it specifically targets only the previous frame?

As an example, say I'm rendering something in constant interpolation, so there is only really a change after a keyframe is placed. So say I have a keyframe at frame 20 and another keyframe at frame 30.

So I ask the addon to render only 2 frames (20 and 30) and I want specifically for it to copy only frame 20 to fill from 21-29 without using 30 for the frames that would be closer to it (as in 26-29).

So is there a way or could you add the option to only go from the frame previously rendered instead of the frames "closer"?

**Comment by p2or** [comment]
Hi @AlfyAnahuac,

by default, frame 20 is copied until frame 30 is reached so you get exactly what you describe right? Not a native speaker but that's what 'closest frame' means :) If you have suggestions for improving the documentation, please let me know or just open up a pull request. I would greatly appreciate any improvement in that regard.

Cheers,
Christian

**Comment by p2or** [comment]
Hi @AlfyAnahuac,

I just updated the documentation and hope this is a better description of what the operator is doing. If something is still unclear or could be improved, please let me know. 

Note that yesterday I also found a small bug and updated the latest release. If you'd like to use it and just want to fill the gaps of the given sequence, make sure *Ignore Scene Range* property to the left is enabled ([as now also described in the documentation](https://github.com/p2or/blender-loom#encode-image-sequence-dialog-ctrlshiftf9)). 

Cheers,
Christian

**Comment by AlfyAnahuac** [comment]
Ah I see. Closest is a bit confusing but the change makes it clearer now. Thank you!
