### ISSUE TITLE
no alpha render in Batch Dialog even if I choose 4444 XQ

### ISSUE THREAD

**Issue by rafek-finearts** [p2or/blender-loom#43]
no alpha render in Batch Dialog even if I choose 4444 XQ, however it works as expected if I rendered it by win+shift+F9, so I have to render the frames first than encode the alpha video by win+shift+F9
by the way Iam using the latest version

**Comment by p2or** [comment]
Hi @rafek-finearts,

thanks for your report. Which version of ffmpg are you using?

Cheers,
Christian

**Comment by rafek-finearts** [comment]
The latest version

**Comment by p2or** [comment]
Hi @rafek-finearts,

cool, should now work as expected (tested with `5.0.1-tessus`).

Cheers,
Christian

**Comment by rafek-finearts** [comment]
Awesome, thanks!
