### ISSUE TITLE
loom batch rendering dont work with placeholders option?

### ISSUE THREAD

**Issue by Chrisyahya** [p2or/blender-loom#45]
Hello. I love your addon, it helps me alot. But there is one thing : i run 2 computers rendering on same animation. Usually i use overwrite disabled and placeholder enabled.

Place holders will make an empty file frame, while being rendered so other computer will skip that frame (so wont make 2 computers working on same frame).

but loom batch rendering apparently dont make placeholders, so it could end up rendering on same frames. Or maybe i misconfigured? thank you!

**Comment by p2or** [comment]
Hi @Chrisyahya,

thanks for your report. This should work out of the box if 'Overwrite' is disabled and the file exists on disk, make sure the file path is correct. However, while testing I noticed a tiny little inconsistency for batch rendering and [created a new branch](https://github.com/p2or/blender-loom/tree/skip-existing-frames) to address this. I am not sure whether this is your issue though.

If you have the time, please [download *Loom* from there](https://github.com/p2or/blender-loom/tree/skip-existing-frames) using the download button and report back. If that does not solve your issue, please provide a simple file to test against, thanks.

Cheers,
Christian

**Comment by Chrisyahya** [comment]
@p2or hello! I tried the placeholder addon version and it worked **as i intend**. **Thank you!**
just a very minor caveat when i cancelled the rendering prematurely, the placeholder still exists, and when retry render, it skipped the placeholder images. 
But, it's alright! the original blender renderer also doing this, i'll delete the place holder manually.

skipping frame text in CLI is nice addition though, so i could track is it skipping correctly.

**Comment by p2or** [comment]
Hi @Chrisyahya,

great, thanks for testing. Since you can kill the terminal at any time, I see no way to remove the non-rendered placeholder at some point. We could check the image size before rendering, but that might be overkill and could affect the overall computation time, I guess. As you mentioned, it shouldn't take too long to sort the images by size in the file browser and then simply delete those with a size of 0kb manually before rendering. Anyway, if you have another or even better idea for this, please let me know. I'm glad it's working now.

Cheers,
Christian

**Comment by Chrisyahya** [comment]
Update : Loom sometimes skipped place holders.

Weird. it's like, the loom working on frame 100. the it done rendering frame 100, going to 101, and suddenly loom after creating placeholder of frame 101, it would go to 102 and rendering. So it make few frames 0Kb data. Happens at random event.

**Comment by p2or** [comment]
Hi @Chrisyahya,

interesting, difficult to reproduce though. Could you please provide a minified blend-file for debugging?

Thanks,
Christian
