### ISSUE TITLE
Feature Suggestion: render token add support for date and time

### ISSUE THREAD

**Issue by Zijian-Wang** [p2or/blender-loom#51]
Hi, 

Thanks for making this plugin. 

I tried to add globals like _$MM_ to _datetime.datetime.now().month.strftime("%m")_ but it turned out to be false when being evaluated, so instead of having the current month number, I would get _NO-MM_ in the file name. 

I tried to add _import datetime_ in the python file but it doesn't change anything. Could you consider adding support for date time in presets? 

I would suggest token naming be following: 
        "$YYYY": datetime.datetime.now().strftime("%Y"),
        "$YY": datetime.datetime.now().strftime("%y"),
        "$MM": datetime.datetime.now().strftime("%m"),
        "$DD": datetime.datetime.now().strftime("%d"),
        "$hh": datetime.datetime.now().strftime("%H"),
        "$mm": datetime.datetime.now().strftime("%M"),
        "$ss": datetime.datetime.now().strftime("%S"),

**Comment by p2or** [comment]
Hi @Zijian-Wang,

you just forgot to import the `datetime` module in the first place, see the provided `$TIME` expression for reference. In this case you can use e.g. `time` or `datetime` modules:

- `$YYYY`: `exec("import time") or time.strftime("%Y")`
- `$YYYY`: `exec("from datetime import datetime") or datetime.now().strftime('%Y')`
- `$MM`: `exec("import time") or time.strftime("%m")`
- `$MM`: `exec("from datetime import datetime") or datetime.now().strftime('%m')`
- ...

<img width="544" alt="Screenshot 2023-05-30 at 18 59 46" src="https://github.com/p2or/blender-loom/assets/512368/ada99e95-d098-43a1-bbd6-cf24602c81f6">


both expressions resolve to `2023` and `05` and should work for all you other requirements as well. Does this help?

Cheers,
Christian

**Comment by Zijian-Wang** [comment]
Tried it, and it worked as I expected. I'm pretty new to both python and blender and thank you so much for this detailed answer! Have a great week!  🥇 😄

**Comment by p2or** [comment]
You're welcome, glad I could help.
