### ISSUE TITLE
addon cant find render_presets

### ISSUE THREAD

**Issue by 4436726avn** [p2or/blender-loom#52]
loom doesnt even create "loom" folder under scripts folder
![Untitled](https://github.com/p2or/blender-loom/assets/40879139/a658624d-6ec5-4287-b7ed-7ceb133b53e4)

**Comment by p2or** [comment]
Hi @4436726avn,

thanks for your report. Just fixed the issue - if you have the time, please download Loom using the green download button and report back.

Cheers,
Christian

**Comment by p2or** [comment]
Hi again,

just had some time to test the [patch](https://github.com/p2or/blender-loom/commit/b9af15a8c796c261f489e2354438ac5bc4285f4e) in _Windows_ and it looks good to me. If you find another error, just let me know and I'll reopen this issue, closing for now.

![Annotation 2023-06-10 193723](https://github.com/p2or/blender-loom/assets/512368/bbffc9b2-56c3-4296-95ae-853c32dcdba8)

Cheers,
Christian

**Comment by 4436726avn** [comment]
the patch worked, however the errors still appear (same image above) after hitting "OK" button on rendering panel. 1 more problem with cmd rendering is i'm using pushbullet, now every frame gets rendered, blender sends a complete signal to my pc and that isn't what i want. So can you make it only send signal after all the rendered images are completed?

**Comment by p2or** [comment]
Hi @4436726avn,

> the patch worked, however the errors still appear (same image above) after hitting "OK" button on rendering panel. 

Hard to reproduce - no popups here when rendering, I cannot confirm. If you still get the same error message with the incorrect path from above, make sure you remove all created presets from before within the loom folder. You can click the film roll icon on the top let of the panel to open up the folder for convinience.

>1 more problem with cmd rendering is i'm using pushbullet, now every frame gets rendered, blender sends a complete signal to my pc and that isn't what i want. So can you make it only send signal after all the rendered images are completed?

interesting, even when rendering via commandline? I guess that notifications are written in C and there is no chance to redirect them via python, we'll see, I'll take a look when I have time.

Cheers,
Christian

**Comment by 4436726avn** [comment]
there is still not "loom" folder under presets folder though. But the render is working so i guess it...fine?

**Comment by p2or** [comment]
Hi @4436726avn,

yes, should be fine. Just make sure you've got the latest version (0.9.0) installed, remove all items you had created before, restart blender and create new presets to work with. To be on the safe side, you can also delete the entire presets folder.

When you add a new item to the presets, the folder should be created automatically and if you click the film roll icon as suggested it should open up the windows explorer on that path (see my screenshot above) which confirms that all is working as expected. Sorry for the confusion, had forgotten to test that feature on _Windows_ before releasing it.

Hope that helps,
Christian
