### ISSUE TITLE
Render specific Keyframes_Where is the Limit by Object Selection toggle?

### ISSUE THREAD

**Issue by MidGoldenFish** [p2or/blender-loom#54]
![image](https://github.com/p2or/blender-loom/assets/137877837/f6da572c-e212-4fc4-98b5-9f8b9417095d)

I can't find the button to toggle Limit by Object Selection, so loom render all object's selected keyframes.Anyone knows where it is?
Thankyou~

**Comment by p2or** [comment]
Hi @MidGoldenFish,

you can find the toggle switch to the left of the actual button: 

![Screenshot 2023-06-27 at 16 54 58](https://github.com/p2or/blender-loom/assets/512368/4958e1bb-5ef6-4e04-9cbc-d2788b5a06fd)

Sorry, probably my mistake, forgot to add a picture to the documentation where to find it exactly. Does this work?

Cheers,
Christian

**Comment by MidGoldenFish** [comment]
Oh yes！ Thank you very much!

**Comment by p2or** [comment]
Ez, you're welcome.
