### ISSUE TITLE
higher than 9999 frames, it does not automatically detect unrendered frames

### ISSUE THREAD

**Issue by rafek-finearts** [p2or/blender-loom#55]
Thanks for your effort the issue is if I am rendering from a start frame higher than 9999 it does not automatically detect unrendered frames because it has more than 5 digits

**Comment by p2or** [comment]
Hi @rafek-finearts,

sorry for the delay. 

> if I am rendering from a start frame higher than 9999 it does not automatically detect unrendered frames because it has more than 5 digits

I guess you haven't specified the number of digits in your output path right? Without specifying anything, Blender's default is `4` (up to `9999`), see the [manual](https://docs.blender.org/manual/en/latest/render/output/properties/output.html). For frame numbers above `9999`, just add `5` placeholders `#####` to the regular output path (w/wo the file extension) and _Loom_ is able to detect your sequence:

<img width="554" alt="Screenshot 2023-07-11 at 09 36 29" src="https://github.com/p2or/blender-loom/assets/512368/0c9c11c3-f89e-4702-8b7f-9fce51c7081b">


Does this help?

Cheers,
Christian

**Comment by rafek-finearts** [comment]
Thanks it is very helpfull

**Comment by p2or** [comment]
@rafek-finearts Great!
