### ISSUE TITLE
i got the following error after hitting render sequence

### ISSUE THREAD

**Issue by Fsorian** [p2or/blender-loom#57]
```
Python: Traceback (most recent call last):
  File "C:\Users\Mitarbeiter\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\loom.py", line 1219, in execute
    bpy.ops.loom.render_terminal(
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.6.1.0_x64__ppwjx1n5r4v9t\Blender\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Mitarbeiter\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\loom.py", line 3644, in execute
    bpy.ops.loom.run_terminal( 
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.6.1.0_x64__ppwjx1n5r4v9t\Blender\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties:  LOOM_OT_run_terminal.argument_collection error converting a member of a collection from a dicts into an RNA collection, failed with: TypeError: Converting a Python list to an RNA collection: keyword "type" missing
Location: C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.6.1.0_x64__ppwjx1n5r4v9t\Blender\3.6\scripts\modules\bpy\ops.py:113
```

**Comment by p2or** [comment]
Hi @Fsorian,

just updated to the latest and greatest blender version on win 10 (3.6.1), did a quick testrender using the commandline as well as the batch dialog and everything worked like a charm. Could you please add a bit more information about your setup and your blender version? Are you using a custom build? Does _Loom_ work with the release version?

Cheers,
Christian

**Comment by Fsorian** [comment]
It worked for mee too the first time i used it. I'll try further to find what is causing the error. thanks for the quick reply
Blender_3.6.1.0_x64

OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-VITI091
System Manufacturer	HP
System Model	HP Z2 Tower G5 Workstation
System Type	x64-based PC
System SKU	2N2C1EA#ABD
Processor	Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz, 3696 Mhz, 10 Core(s), 20 Logical Processor(s)
BIOS Version/Date	HP S50 Ver. 01.04.10, 20.04.2023
SMBIOS Version	3.2
Embedded Controller Version	9.08
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Product	8750
BaseBoard Version	KBC Version 09.08.17
Platform Role	Workstation
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	Germany
Hardware Abstraction Layer	Version = "10.0.22621.1413"
User Name	DESKTOP-VITI091\Mitarbeiter
Time Zone	W. Europe Daylight Time
Installed Physical Memory (RAM)	32,0 GB
Total Physical Memory	31,8 GB
Available Physical Memory	20,8 GB
Total Virtual Memory	31,9 GB
Available Virtual Memory	15,3 GB
Page File Space	100 MB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Not enabled
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by p2or** [comment]
Hi @Fsorian,

based your command line output I guess there is something wrong with your Blender version (again it seems like there is a custom build installed on your workstation so the chances are good that something is wrong).

I'd suggest try the regular 3.6.1 LTS from: https://www.blender.org/download/ and report back.

Cheers,
Christian

**Comment by Fsorian** [comment]
Hi Christian,

Thanks for your reply. Thankfully, following your instructions solved the
issue. The version I was using was installed through the Windows store.

Have a great one,
Fernando

**Comment by p2or** [comment]
Great @Fsorian! Thanks for keeping me posted. Cheers, Christian
