### ISSUE TITLE
Batch Render and Encode not working with EXR file formats

### ISSUE THREAD

**Issue by TimB-com** [p2or/blender-loom#6]
Dear p2or,

First off, I just want to say how helpful your addon is to so many people, Loom provides a simple and elegant solution customised batch rendering in Blender, so thank you very much for creating Loom.

I did want to bring to your attention a small issue I have encountered in Loom 0.3 in Blender 2.80 (Windows 10, 64bit) when utilising 'Batch Render and Encode'

Encoding to any available codec _when_ the blender file output is set to OpenEXR fails the encoding, returning the error 

> '[prores @ 00000214f7913040] encoding with ProRes Proxy/LT/422/422 HQ (apco, apcs, apcn, ap4h) profile, need YUV422P10 input' 

This appears to be specific to the 'Batch render and encode' option as utilising 'Encode Image Sequence' on the same EXR sequence is successful. 

When the blender file output is set to .JPG, the encoding part of 'Batch Render and Encode' is successful. 

Best regards,
Tim

**Comment by p2or** [comment]
Hey Tim,

sorry for the delay. Many thanks for your kind words, I'm glad to hear that this kind of *niche tool* is useful to others too. Also thanks for this nice report, didn't noticed that.

It seems that *prores decoder* options have changed in newer versions of FFmpeg. I tried to fix it using `prores_ks` decoder and created a new [pre-release](https://github.com/p2or/blender-loom/releases/tag/0.3-2.81) to play with. It fixes the issue for now, the encoded files are working in Nuke and the metadata seems to be fine, but it needs some serious testing though. If you have the time please report back whether the patch works or if you encounter any other issues. Thanks.

Best regards,
Christian

**Comment by TimB-com** [comment]
Hey Christian, your fix works perfectly! I've only tested it using the same method that was producing the error beforehand and will continue to test it under other situations but so far it's looking good, thank you once again for creating a fantastic addon _**and**_ putting in the equally commendable time and effort to maintaining it.
