### ISSUE TITLE
Blender crashing during loom render trigger

### ISSUE THREAD

**Issue by beyond9thousand** [p2or/blender-loom#61]
I've noticed that Blender tends to crash randomly during the nth trigger/call to loom for rendering (clicking ok)

I am running 3.5.1, any ideas about what could be causing it? The addon is incredibly useful and I don't want to use other convoluted addons for the same purpose.

**Comment by p2or** [comment]
Hi @beyond9thousand,

honestly, I have no idea - using it all day and never noticed something like this. In general *Loom* just gives the engine some instructions for rendering, so I can't imagine right now why this would cause Blender to crash over time. Based on your report, I can only recommend keeping an eye on your memory as this is the most common cause of errors in Blender in my expierence. When it gets too heavy, I recommend using the commandline feature. Does this help?

Cheers,
Christian

**Comment by beyond9thousand** [comment]
memory being my RAM or VRAM? I have 32GB at work and 64 GB at home. VRAM at work is about 8GB. Are there any addons that could potentially conflict with loom?

alternatively if you could show me your build with addons/lack thereof, would be helpful

**Comment by p2or** [comment]
Hi @beyond9thousand,

> Memory being my RAM or VRAM? I have 32GB at work and 64GB (RAM) at home. VRAM at work is about 8GB

It doesn't matter how much you have, in my experience Blender tends to crash when things get tight.

> Are there any addons /types of addons that could potentially conflict with loom?

Not that I know of, nor do I see any reason for a potential conflict.

> Alternatively if you could show me your blender build with addons/lack thereof, would be helpful

Gladly, if that helps you. I'm running the latest LTS with a small number of add-ons, nothing special - *fSpy*, *Facebuilder*, *Loom* and some that come with Blender e.g. *F2*, *LoopTools*, *Tissue*, *Btracer*, *Turnaround camera* are enabled as well.

Hope this helps. If there is anything else I can do for you in this regard, just let me know.
Christian

**Comment by beyond9thousand** [comment]
Hmm, this along with what you've previously told me (blender not crashing randomly due to loom) leads me to believe that it could possibly be an add-on causing the crash since most of the project setups I have are extremely optimised. (Instancing, organizing, turned off collections etc)

Blenderkit in particular has the tendency to crash blender (independently)

But thanks for sharing your list. I'll get back to you over the weekend after testing out a few things

**Comment by beyond9thousand** [comment]
[SMNS_ANM_Menv0c.crash.txt](https://github.com/p2or/blender-loom/files/12764674/SMNS_ANM_Menv0c.crash.txt)

Was able to grab this crash report from a few minutes ago, does this help? I can't see anything obvious

**Comment by p2or** [comment]
Hi @beyond9thousand,

seems to me that Blender crashes when you change the actual shading mode, so I don't see any relation at the moment. I would suggest monitoring your video card and ram. Closing and reopening Blender from time to time might help as well (empties the ram). To save resources, I would suggest using the command line rendering feature of _Loom_.

Cheers,
Christian

**Comment by beyond9thousand** [comment]
Does the command line version support compositor nodes? I almost always use file output nodes for the render results (passes etc)

**Comment by p2or** [comment]
Hi @beyond9thousand,

_Loom_ renders the scene as it is. If there are compositing nodes, then so be it. Just click the little checkbox and you'll see. 

Cheers,
Christian

**Comment by beyond9thousand** [comment]
I was able to consistently run loom through the commandline for multiple batches consecutively. You were probably right!
