### ISSUE TITLE
Batch render blend files without encoding?

### ISSUE THREAD

**Issue by beyond9thousand** [p2or/blender-loom#62]
Does loom already have an option to do this? Apologies in advance, been looking for it since two days

**Comment by p2or** [comment]
Hi @beyond9thousand,

sure, that's the default - just add your blends to the list and hit <kbd>OK</kbd>. 

To additionally encode your image sequences, you have to enable the encoding flag <img width="23" alt="encoding-flag-disabled" src="https://github.com/p2or/blender-loom/assets/512368/e7fae82f-a0e3-4bd5-8b54-c20157d9ee08"> of each list entry. I've just changed the description to clarify, see: https://github.com/p2or/blender-loom#notes

If you have a better idea to make this clear for everyone, just let me know.

Cheers,
Christian

**Comment by beyond9thousand** [comment]
Checks out, thanks! I think its an equal tradeoff either way. My alternative suggestion would have been to have it written as 'Batch Render' rather than '& encode'
