### ISSUE TITLE
Blender 4.1 throws an error

### ISSUE THREAD

**Issue by luckychris** [p2or/blender-loom#67]
Unfortunately your great add-on doesn't work anymore in blender 4.1. Looks like the API changed. Error -> image_sequence if you try to do a batch render.

<img width="568" alt="image" src="https://github.com/p2or/blender-loom/assets/232549/f8d7e4ff-185d-4c12-958d-976731556a01">

**Comment by p2or** [comment]
Hi @luckychris,

did you restart Blender after the installation? Could you please try to save the user preferences after the installation, restart Blender and call the batch dialog again?

Cheers,
Christian

**Comment by luckychris** [comment]
Hi Christian,

i am sorry i disturbed you. It works now. Also i don't understand why this helped. ;) But i am glad it does.

Have a nice Sunday
Christoph

**Comment by luckychris** [comment]
Thank you!!

**Comment by luckychris** [comment]
thank you!!

**Comment by p2or** [comment]
Hi @luckychris,

no problem - glad it works. If you are interested: You have to restart Blender because the add-on is not yet activated for the new instance of Blender which is called via the command line at this point (the reason why the `image_sequence` operator is missing as stated in your console).

Cheers,
Christian

**Comment by p2or** [comment]
Hi @luckychris,

FYI: as of the [latest commits](https://github.com/p2or/blender-loom/commits/master) you don't necessarily have to restart Blender after installing *Loom* anymore (not yet completely sure for all possible cases though).

Cheers,
Christian

**Comment by luckychris** [comment]
> Hi @luckychris,
> 
> FYI: as of the [latest commits](https://github.com/p2or/blender-loom/commits/master) you don't necessarily have to restart Blender after installing _Loom_ anymore (not yet completely sure for all possible cases though).
> 
> Cheers, Christian

That's great!
