### ISSUE TITLE
GLobals (file output) seem to not work in Compositor file output nodes

### ISSUE THREAD

**Issue by luismglopes** [p2or/blender-loom#69]
Hi!
First, thanks for creating this addon. It is great.

But I want to set some of the globals in the output nodes in compositor and it seems to not work there.
I also added a $VER variable for the blend file version and it works great in the blender output but not in the compositor nodes.
Maybe I am doing something wrong.

Again, thank you for the addon!
Cheers,
Luis

**Comment by p2or** [comment]
Hi @luismglopes,

thanks for your report and your kind words! 

Unfortunately, I can not confirm or reproduce your issue. I quickly tested  the output based on the provided `$BLEND` variable using a 'File Output' node, and the file names as well as the folder are written properly, see the attached clip and blend file:

https://github.com/p2or/blender-loom/assets/512368/726a0ee9-38fd-4db5-80fb-96e8ca44e476

[untitled.blend.zip](https://github.com/p2or/blender-loom/files/13367560/untitled.blend.zip)

Does this help? If that doesn't help, could you please provide your expression and what do you expect the names to be? 

Thanks,
Christian

**Comment by luismglopes** [comment]
thank you for your fast response!
I see the same, but if I press F12 to render, blender will save the output nodes in the compositor, but it will not name the folders as expected. In this case, if you just press F12 it will save in $BLEND and not the name of the file. Maybe I have some permissions issue or something else.
If you press F12 does it create a render/untitled _v1/ folder and file? I get what I have in the attachment.

![Screenshot_1](https://github.com/p2or/blender-loom/assets/114748037/6393f955-174e-4506-b8bb-5e7eed1bfcdb)

**Comment by luismglopes** [comment]
and my expression is : $VER = bpy.path.basename(bpy.context.blend_data.filepath)[-9:-6] 
which for a file name such as untitled_v001.blend will give 001. I use this a lot to save my renders in versioned folders.

**Comment by p2or** [comment]
Hi @luismglopes,

> I see the same, but if I press F12 to render, blender will save the output nodes in the compositor, but it will not name the folders as expected. In this case, if you just press F12 it will save in $BLEND and not the name of the file. Maybe I have some permissions issue or something else.

Yeah, you have to use *Loom* for rendering in order to make it work (instead of the regular <kbd>F12</kbd> render operator). Open up the file and call e.g. the ['Render Image Sequence Dialog'](https://github.com/p2or/blender-loom#render-image-sequence-dialog-ctrlshiftf12) using <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>F12</kbd> and you'll see that this is going to work.

> and my expression is : $VER = bpy.path.basename(bpy.context.blend_data.filepath)[-9:-6]
which for a file name such as untitled_v001.blend will give 001. I use this a lot to save my renders in versioned folders.

Thanks, should work fine.

Does this help?

Cheers,
Christian

**Comment by luismglopes** [comment]
Yep, that worked great! thanks again. Maybe having a shortcut to make loom render just the current frame would be helpful, without a dialogue. It would spare a few clicks ;)

**Comment by p2or** [comment]
Hi @luismglopes,

great! Any proposals are welcome...

Cheers,
Christian
