### ISSUE TITLE
Does not detect Grease Pencil keyframes. 

### ISSUE THREAD

**Issue by Rokazas** [p2or/blender-loom#7]
Says empty selection.
![image](https://user-images.githubusercontent.com/3463981/77431694-baf86200-6de5-11ea-84d0-2c14c86d5a12.png)

**Comment by p2or** [comment]
Hi @Rokazas,

I just implemented all possible modes of the *Dopesheet* (*Grease Pencil, Action, Shapekey etc.*). Good news is that it should work for the *Grease Pencil* now. 

![ds](https://user-images.githubusercontent.com/512368/77571997-89a79100-6ece-11ea-9c9d-9ed08e141788.png)

However, I never used the *Grease Pencil* before so... If you have the time please test the **updated version (0.4)** and report back whether the patch works. Thanks.

Cheers,
Christian

**Comment by Rokazas** [comment]
Thank You,Christian, for such a fast fix !
Works perfectly now.

![image](https://user-images.githubusercontent.com/3463981/77619300-9cf34480-6f40-11ea-9f78-09283ec3d810.png)
