### ISSUE TITLE
Feature request: Viewport rendering option

### ISSUE THREAD

**Issue by Ulf3000** [p2or/blender-loom#70]
hey man , great addon ! thanx alot ! rendering only selected keyframes is an option which is is surely missing from native blender and you added this important feature! 

i have one request though , is it possible to add an option to use "viewport rendering" instead of "normal rendering" ? 
I often use viewport rendering becasue A) its like 10 times faster than normal, B) it outputs the exact visual representation from the viewport and C) you can just isolate an object, render it and leave isolation mode , no need to fiddle with the outliner render properties for each object.

**Comment by p2or** [comment]
Hi @Ulf3000,

thanks for your feature request and your kind words - glad that the add-on is also useful to others. Regarding your question: In Blender the viewport is rendered using the [workbench engine](https://docs.blender.org/manual/en/latest/render/workbench/introduction.html) which you can also use for rendering:

<img width="428" alt="Screenshot 2023-12-16 at 16 42 37" src="https://github.com/p2or/blender-loom/assets/512368/fb444b43-31b1-40a4-8c9c-588a5c6e5e89">

Does that help you? Otherwise, please be more specific about what do you mean by viewport rendering, thanks.

Cheers,
Christian

**Comment by Ulf3000** [comment]
no i meant **bpy.ops.render.opengl** = viewport rendering 

![grafik](https://github.com/p2or/blender-loom/assets/10765339/57227418-6bf3-47f7-91d0-d2e5ba592259)

Rendering of the eeve viewport (with realtimecompositor). Im getting great results out of it.

**Comment by p2or** [comment]
Hi @Ulf3000,

if this is really a thing and helps others in their work too, I'm in. I created a new [flipbook-branch](/p2or/blender-loom/tree/render-flipbook) to play with and get the ball rolling. For now you can either use <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>F10</kbd> or go to *Render > Loom > Render Flipbook (OpenGL)*:

<img width="523" alt="Screenshot 2023-12-22 at 22 18 39" src="https://github.com/p2or/blender-loom/assets/512368/18776991-0c9f-45e3-bf03-fc5d09cb5abc">

If you have the time, please download the add-on from there and report back. If you have better ideas for placement, name, handling etc. let's just discuss it.

Cheers,
Christian

**Comment by Ulf3000** [comment]
works perfect here, just the line 5808 needs to be commented out, otherwise the script fails. 
i used crtl+shift+F10 and then put in arbritrary numbers. it rendered them fine and opened the folder afterwards. Just like the normal version.

If that could be implemented to the dopesheet button too would be nice. 

One thing to note, when i use realtime compositor  and have a blended texture in the compositor it will render that textures at the wrong size depending on the actual zoom level. I dont know if thats a bug which will be ironed out or not. 
![grafik](https://github.com/p2or/blender-loom/assets/10765339/ecb2c8a6-d384-4057-b528-5b2931bc9544)

turns into this 
![grafik](https://github.com/p2or/blender-loom/assets/10765339/aa6e3b45-941f-415b-bffc-4ec9edda547a)

so i always do a   

bpy.ops.view3d.view_center_camera()
 
and a
 
bpy.ops.view3d.zoom_camera_1_to_1()

befoer rendering. This ensures that the camera is zoomed fully and sits directly in the middle. Overlays , imported videos etc. will now render in the right location at the right size. 
![grafik](https://github.com/p2or/blender-loom/assets/10765339/bfda6bb9-3132-4c4a-9e79-abe7d79d2ddf)

**Comment by p2or** [comment]
Hi @Ulf3000,

> just the line 5808 needs to be commented out

Thanks, a leftover from my tests that I just removed (7900e8f). 

> If that could be implemented to the dopesheet button too would be nice.

To put there - it needs a name, an icon, a description and so on... If you have an idea, just let me know.

> so i always do a `bpy.ops.view3d.view_center_camera()` and a `bpy.ops.view3d.zoom_camera_1_to_1()`

Good to know - something we could put on the panel and execute automatically for the user (if truly relevant). I think, having an option on the panel to disable all [overlays](https://docs.blender.org/manual/en/latest/editors/3dview/display/overlays.html) while rendering automatically would be helpfull as well. Do you agree?

Anyway, this feature is a lot of work and not easy to maintain over the years. Your current findings feel more like quick notes to me so I would ask you, please just work with it on a longer period and write down all your thoughts in a comprehensible way before we push this even further or perhaps make a sketch of what it might look like and especially how this could work for others too, thanks.

Cheers,
Christian

**Comment by Ulf3000** [comment]
> I think, having an option on the panel to disable all [overlays](https://docs.blender.org/manual/en/latest/editors/3dview/display/overlays.html) while rendering automatically would be helpfull as well. Do you agree?

Sure , most of the time it would be enabled (for me). i toggle it with a shortcut but thats convinient. 

> , please just work with it on a longer period and write down all your thoughts

will do , thanx for your hardwork

**Comment by p2or** [comment]
Hi @Ulf3000,

good news, overlays are now [automatically hidden](48acbab) during rendering as discussed and can be switched on if required:

<img width="500" alt="Screenshot 2023-12-27 at 18 19 33" src="https://github.com/p2or/blender-loom/assets/512368/ded39b14-90ca-4057-9fba-c81e48e79060">

However, when I tried to implement your camera settings (maximizing the camera bounds as well as setting the 1:1 ratio), I found that this has no effect on the actual result - regardless of the zoom level, there is technically no difference:

![Comp_cameraBounds](https://github.com/p2or/blender-loom/assets/512368/6644e9e5-d26f-4d49-92b2-47f21a26cc8e)

Am I missing something here? Or is this just your personal preference?

Cheers,
Christian

**Comment by Ulf3000** [comment]
> Am I missing something here? Or is this just your personal preference?

In the example i posted , i overlayed an image texture( a gradient made in photoshop) with the realtime compositor. If the image isnt zoomed 1:1 then that gradient will not apply to the whole render image but just as a box in the middle depending on the zoom level (the smaller the camera is zoomed the smaller that rectangle will be ). 

So its ONLY to fix this shortcoming of the realtime compositor.

**Comment by p2or** [comment]
Hi @Ulf3000,

FYI: In my tests, the image renders perfectly fine using our new _flipbook feature_ without adjusting the camera of the viewport - even if the viewport is tiny and the image is not displayed as expected when in camera view, the result is actually correct. Example of a comped image on top of the render layer _(scene with comp on the left, render result on the right)_:

![Test-CameraOptim_v01](https://github.com/p2or/blender-loom/assets/512368/c70ee62c-2f7c-4320-85da-fe8bac369de4)

If you still see a need for optimization, please let me know.

Cheers,
Christian

**Comment by p2or** [comment]
Hi @Ulf3000,

to support rendering of markers and keyframes, I've just added a new property to the popover in the timeline that allows to switch between normal and flipbook rendering:

<img width="263" alt="Screenshot 2024-02-05 at 16 26 00" src="https://github.com/p2or/blender-loom/assets/512368/b57b39e8-3722-44ca-ac3d-8e4c11523412">

What do you think? Does that work for you? Or do you have a better idea?

Cheers,
Christian

**Comment by Ulf3000** [comment]
> Hi @Ulf3000,
> 
> to support rendering of markers and keyframes, I've just added a new property to the popover in the timeline that allows to switch between regular and viewport rendering:
> <img alt="Screenshot 2024-02-05 at 16 26 00" width="263" src="https://private-user-images.githubusercontent.com/512368/302342125-b57b39e8-3722-44ca-ac3d-8e4c11523412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNTU3ODcsIm5iZiI6MTcwNzI1NTQ4NywicGF0aCI6Ii81MTIzNjgvMzAyMzQyMTI1LWI1N2IzOWU4LTM3MjItNDRjYS1hYzNkLThlNGMxMTUyMzQxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQyMTM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWZjNWZmOTFlN2E4YzU0ODE5MjdlMTgxODM4MjMzMjEwMGZiZThhNzhiYzNiYTExMmJlNDllMzA4MmEyOTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YErFLktbDMfRav5fgmAJI-dMG53c2HL9exhIleDEhqQ">
> 
> What do you think? Does that work for you? Or do you have a better idea?
> 
> Cheers, Christian

hi i downloaded loom.py from the branch but that icon doesnt appear for me 
![grafik](https://github.com/p2or/blender-loom/assets/10765339/aba0feeb-abb7-4781-aa38-335abbd8c25e)


----

also the issue above is not resolved for me , can you share the test blend file ?

**Comment by p2or** [comment]
Hi @Ulf3000,

> hi i downloaded loom.py from the branch but that icon doesnt appear for me. 

Cannot confirm, works fine. Any error message in the console?

![ezgif-5-79e4f5cbf8](https://github.com/p2or/blender-loom/assets/512368/06a0919d-92b1-4bf8-bf2c-691d058456bc)

> the idea is good , if it keeps being selected. 

Yep, the state is stored per scene.

> also the issue above is not resolved for me , can you share the test blend file ?

Sure, here it is: [flipbook-feature_clean.blend.zip](https://github.com/p2or/blender-loom/files/14186625/flipbook-feature_clean.blend.zip).

Cheers,
Christian

**Comment by Ulf3000** [comment]
> Hi @Ulf3000,
> 
> > hi i downloaded loom.py from the branch but that icon doesnt appear for me.
> 
> Cannot confirm, works fine. Any error message in the console?
> 
> ![ezgif-5-79e4f5cbf8](https://private-user-images.githubusercontent.com/512368/302791635-06a0919d-92b1-4bf8-bf2c-691d058456bc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5ODk5MzYsIm5iZiI6MTcwODk4OTYzNiwicGF0aCI6Ii81MTIzNjgvMzAyNzkxNjM1LTA2YTA5MTlkLTkyYjEtNGJmOC1iZjJjLTY5MWQwNTg0NTZiYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQyMzIwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjMxZGU2NmUwMTRmZDU5NTNkN2IxOWIwNDI2ZDE3YzJiZTdkOTM1ZmRjMTA2MDg4MzgxNDc1NDJhODk5ZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kOAQNQOSXxsu-jrkVAsERVjXxDVS07fZGMbpDJnDUR4) [ ](https://private-user-images.githubusercontent.com/512368/302791635-06a0919d-92b1-4bf8-bf2c-691d058456bc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5ODk5MzYsIm5iZiI6MTcwODk4OTYzNiwicGF0aCI6Ii81MTIzNjgvMzAyNzkxNjM1LTA2YTA5MTlkLTkyYjEtNGJmOC1iZjJjLTY5MWQwNTg0NTZiYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQyMzIwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjMxZGU2NmUwMTRmZDU5NTNkN2IxOWIwNDI2ZDE3YzJiZTdkOTM1ZmRjMTA2MDg4MzgxNDc1NDJhODk5ZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kOAQNQOSXxsu-jrkVAsERVjXxDVS07fZGMbpDJnDUR4) ![ezgif-5-79e4f5cbf8](https://private-user-images.githubusercontent.com/512368/302791635-06a0919d-92b1-4bf8-bf2c-691d058456bc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5ODk5MzYsIm5iZiI6MTcwODk4OTYzNiwicGF0aCI6Ii81MTIzNjgvMzAyNzkxNjM1LTA2YTA5MTlkLTkyYjEtNGJmOC1iZjJjLTY5MWQwNTg0NTZiYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQyMzIwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjMxZGU2NmUwMTRmZDU5NTNkN2IxOWIwNDI2ZDE3YzJiZTdkOTM1ZmRjMTA2MDg4MzgxNDc1NDJhODk5ZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kOAQNQOSXxsu-jrkVAsERVjXxDVS07fZGMbpDJnDUR4) [ ](https://private-user-images.githubusercontent.com/512368/302791635-06a0919d-92b1-4bf8-bf2c-691d058456bc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5ODk5MzYsIm5iZiI6MTcwODk4OTYzNiwicGF0aCI6Ii81MTIzNjgvMzAyNzkxNjM1LTA2YTA5MTlkLTkyYjEtNGJmOC1iZjJjLTY5MWQwNTg0NTZiYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQyMzIwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjMxZGU2NmUwMTRmZDU5NTNkN2IxOWIwNDI2ZDE3YzJiZTdkOTM1ZmRjMTA2MDg4MzgxNDc1NDJhODk5ZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kOAQNQOSXxsu-jrkVAsERVjXxDVS07fZGMbpDJnDUR4)
> 
> > the idea is good , if it keeps being selected.
> 
> Yep, the state is stored per scene.
> 
> > also the issue above is not resolved for me , can you share the test blend file ?
> 
> Sure, here it is: [flipbook-feature_clean.blend.zip](https://github.com/p2or/blender-loom/files/14186625/flipbook-feature_clean.blend.zip).
> 
> Cheers, Christian

sorry man , i mixed up the files. it works alright here:

![grafik](https://github.com/p2or/blender-loom/assets/10765339/2fa47a89-886c-46a4-9654-d6aa39c28849)



are selected keyframes messed up though ? i get other numbers than the selected keyframes:

![grafik](https://github.com/p2or/blender-loom/assets/10765339/4c039bdf-d63d-4628-adce-73dbe2c6a6f3)

**Comment by p2or** [comment]
Hi @Ulf3000,

please make sure that no keyframes from other objects in the scene are selected by activating the _Limit by object selection_ toggle. Just tested and cannot confirm this behavior. If this does not work for whatever reason, please report back. 

![Screenshot 2024-02-27 at 09 35 21](https://github.com/p2or/blender-loom/assets/512368/b0cf9b68-d336-4b3a-86c7-62aa2edb93b7)

Does everything else work for you?

Cheers,
Christian

**Comment by Ulf3000** [comment]
yes that worked, thanx :
![grafik](https://github.com/p2or/blender-loom/assets/10765339/85062029-d8fc-4104-bb89-807cecd21836)
it were probably selected keyframes in realtime compositor or shader editor which messed it up

**Comment by p2or** [comment]
Hi @Ulf3000,

had the time to test it while working on a project and it works fine for me, hence I think I'm ready to merge this branch into the master in the next few days. Do you have any suggestions for improvement? Is there anything else bothering you? 

Cheers,
Christian

**Comment by Ulf3000** [comment]
go ahead, its been working fine for me since the first iteration. 

the problem above with the realtime compositor and zoom levels is still not resolved for me , but that has nothing to do with your addon. Let the blender devs fix this at core level imo.

It would be cool if we could get OCA(Open Cel Animation format) and/or XDTS (used by opentoonz and toei animation sheet) when using "selected keyframes" rendering, but thats a different feature i guess.

**Comment by p2or** [comment]
Hi @Ulf3000,

> the problem above with the realtime compositor and zoom levels is still not resolved for me , but that has nothing to do with your addon. Let the blender devs fix this at core level imo.

Wouldn't be hard to add a test (we already had one and the code is there) but as you can see in my Nuke screenshot, I can not reproduce it - I can only guess that the resolution of the image you are using is slightly different. Did you test my file?

> Im very happy with your script, the ability to combine selected keyframes and viewport rendering is really awesome for me. I can render animations in mere seconds now.

Hi5!
Christian

**Comment by Ulf3000** [comment]
> I can only guess that the resolution of the image you are using is slightly different. Did you test my file?

yes , same result for me:
![grafik](https://github.com/p2or/blender-loom/assets/10765339/78ddd5df-1c49-4d19-b202-86901a41f491)

see the rectangle in the middle of the image (bokeh blur node was disabled in this viewport render )

**Comment by p2or** [comment]
Hi @Ulf3000,

> click view->viewport render image

Aha, thanks. I guess we are talking about two different things. I naturally assumed that we were talking about our flipbook feature and what I was testing with. Does this also happen when you render the image using _Loom_ and our new flipbook feature? 

Cheers,
Christian

p.s. I can't really test your file because the image is missing.

**Comment by Ulf3000** [comment]
> Hi @Ulf3000,
> 
> > click view->viewport render image
> 
> Aha, thanks. I guess we are talking about two different things. I naturally assumed that we were talking about our flipbook feature (which I tested with). Does this also happen when you render the image using _Loom_ and our new flipbook feature?
> 
> Cheers, Christian
> 
> p.s. I can't really test your file because the image is missing.

its your file, just slightly edited. the spiral shader should be inside. i dont know about the other images i think you forgot to pack them too, but doesnt matter which image is used, the rectangle will always be there. 
The same render result as above when i use ctrl+shift+F10 or the button in timeline.

**Comment by p2or** [comment]
Hi @Ulf3000,

> i dont know about the other images i think you forgot to pack them too,

I've used a regular 'Color Grid' based on the scene resolution which can be generated on the fly, see the [previous screenshot](https://github.com/p2or/blender-loom/issues/70#issuecomment-1871846280).

>  the rectangle will be there IF zoom levels are not at 100%. The same render result as above when i use ctrl+shift+F10 or the loom button in the timeline.

I haven't changed anything in your file except for generating the checkerboard and I unfortunatly still can not confirm. The zoom level is way of in the viewport and it works fine (even with the regular 'Render Viewport' operator in this case), see:

<img width="1439" alt="Screenshot 2024-03-24 at 20 04 29" src="https://github.com/p2or/blender-loom/assets/512368/9616ce3b-ee6a-4889-9283-da024dcc128c">
<br><br>

> but please dont care, you will just waste time ...

Good, agree. Just in case you need the file with the checkerboard for further tests on your machine: [flipbook-feature_clean3.blend.zip](https://github.com/p2or/blender-loom/files/14736496/flipbook-feature_clean3.blend.zip).

Cheers,
Christian

**Comment by Ulf3000** [comment]
i found the difference in our setup 🤦‍♂️🤦‍♂️
your newest file untouched

blender 4.0:
![grafik](https://github.com/p2or/blender-loom/assets/10765339/eed6ff83-341e-4733-a6f6-9d40e7ac6151)

blender 4.1:
![grafik](https://github.com/p2or/blender-loom/assets/10765339/751e71b5-7268-4fff-a80f-4e0f50cd2a58)

blender 4.2:
![grafik](https://github.com/p2or/blender-loom/assets/10765339/86b61cdd-d117-47e8-ab9c-3dee5b6fa31a)

sorry for dragging this out.. i will probably switch to gooengine anyways which is only available as 4.0 release

**Comment by p2or** [comment]
Hi @Ulf3000,

sweet, thanks for letting me know. As Blender 4.2 is in 'Alpha' stage and experimental software at the time of writing this, there is unfortunately nothing I can do for you and would be a waste of time. I'd suggest report this behavior to [developer.blender.org](https://projects.blender.org/blender/blender/issues) in case anyone hasn't already noticed.

Cheers,
Christian
