### ISSUE TITLE
File Path Variables not working on 4.0

### ISSUE THREAD

**Issue by issimissimo** [p2or/blender-loom#71]
Hello, File Path Variables don't work on Blender 4.0

**Comment by p2or** [comment]
Hi @issimissimo,

thanks for your report. Unfortunately I can't confirm or reproduce your issue - just tested on the latest and greatest Blender version and it works for me as expected. Make sure you are using *Loom* for rendering in order to make it work (instead of the regular <kbd>F12</kbd> render operator). Otherwise please add more details to your report or ideally a blend file to test.

Cheers,
Christian

**Comment by issimissimo** [comment]
Hi! First of all many thanks to you for your great job!
I'm actually using Blender 4.02, but unfortunately, when i put "$SCENE" as variable in the file path output, it just replace "$SCENE" with "Scene", not the name of the scene.
![image](https://github.com/p2or/blender-loom/assets/41523122/829e85d7-1173-4b09-b1ae-e278dff337c9)

I'm using Loom for rendering...
![image](https://github.com/p2or/blender-loom/assets/41523122/9c8a9b9b-e7ad-462d-bb5f-3d0685548a81)
...and the .png are saved in the "Scene" named folder (instead of the name of the scene)
![image](https://github.com/p2or/blender-loom/assets/41523122/e8181093-cbb2-48aa-a08a-fe8293e78a1b)

Please look at the screenshot in attachement.
Again, many thanks! Your work is precious!

**Comment by p2or** [comment]
Hi @issimissimo,

thanks for the details. Unfortunately I still can't confirm - works fine for me too, a trusty gif:

![ezgif-5-93639f9d6f](https://github.com/p2or/blender-loom/assets/512368/ba50db10-6161-4def-bfbc-53c1f9417b50)

Resulting file name is `Scene3_0001.exr` as expected, I assume you want to output a different property - if so, which one?

Cheers,
Christian

**Comment by issimissimo** [comment]
Ahh!! Sorry for my misunderstanding... I had idea that "$SCENE" was referred to the file name... my fault!
I'm really sorry to wasted your time with my stupid question, please forgive me.
P.S. is there a way to put the filename as variable?

**Comment by p2or** [comment]
Hi @issimissimo,

> Ahh!! Sorry for my misunderstanding... I had idea that "$SCENE" was referred to the file name... my fault! I'm really sorry to wasted your time with my stupid question, please forgive me.

No problem - glad I could help.

> is there a way to put the filename as variable?

Yes, that's easy - you can use `$BLEND` (one of the defaults):

<img width="480" alt="Screenshot 2024-01-11 at 19 00 04" src="https://github.com/p2or/blender-loom/assets/512368/52526e1b-6e0e-49e6-a066-cec0ef789310">

Cheers,
Christian

**Comment by issimissimo** [comment]
Man, you rock. No words.
Chapeau
Many many many thanks!

**Comment by p2or** [comment]
I am pleased that it helps others in their work too. Cheers!
