### ISSUE TITLE
Feature Request: support for compositor's file output node

### ISSUE THREAD

**Issue by L0Lock** [p2or/blender-loom#73]
Similar to #72 but in comp. It would be great if the variables could be used in the path and file name fields.

![image](https://github.com/p2or/blender-loom/assets/16049822/568e7d81-bf0a-4969-ae8c-cad61797ac0b)

**Comment by p2or** [comment]
Hi @L0Lock,

this is already working, otherwise please report back. All 'File Output' nodes are even displayed as a list on the bottom of the 'Output Panel' to simplify their setup.

Cheers,
Christian

**Comment by L0Lock** [comment]
Indeed, though it doesn't seem to be working:

![image](https://github.com/p2or/blender-loom/assets/16049822/67696680-58c5-4866-8e3d-9120a9004a70)

Since the custom UI only exposes the node's path and not the individual images, I don't know if it is supposed to work on the path only and not the file? If not, it could be a nice addition for anyone making multiple outputs that aren't passes in a multilayer EXR.

**Comment by p2or** [comment]
Hi @L0Lock,

unfortunately I cannot confirm or reproduce your issue - just tested on the latest and greatest Blender version and it works for me as expected: 

<img width="1153" alt="Screenshot 2024-01-13 at 11 36 40" src="https://github.com/p2or/blender-loom/assets/512368/d946bb30-6d76-48dc-b9b5-ed1d11fb1ee7">

Make sure you are using _Loom_ for rendering in order to make it work (instead of the regular <kbd>F12</kbd> render operator) and report back.

Cheers,
Christian

**Comment by L0Lock** [comment]
I just retried with menu Render > Loom > Render Image Sequence (Ctrl Shift F12), it did work.

I used Blender's rendering, because as it worked well with the regular render output setting, I assumed it would work with compositing nodes as well. Do you think it would be possible to make it work with Blender's rendering as well for consistency and QOL? 😊

**Comment by p2or** [comment]
Hi @L0Lock,

> I just retried with menu Render > Loom > Render Image Sequence (<kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>F12</kbd>), it did work.

glad it works.

> I used Blender's rendering, because as it worked well with the regular render output setting

Nope, it doesn't. The replacement of the variables only works when using one of the render operators provided by _Loom_. With the current state of the API, a correct implementation of variables for the regular render operator is impossible or leads to technical nonsense in all my attempts, e.g. there is not even an option to cancel the regular rendering operator.

Regarding QOL: In my opinion it's a bad default (or decision), not having to specify the frame to be rendered :D ... however, it should at least be mentioned in the documentation that the replacement only works when using one of the provided operators, my bad.

Anyway, I am open to all ideas for improvement. If you have a better idea in this regard, please let me know and let's discuss about it.

Cheers,
Christian
