### ISSUE TITLE
File path variables don't work anymore

### ISSUE THREAD

**Issue by issimissimo** [p2or/blender-loom#75]
Hello! I've saved a new version of the file and from now the path variables don't work anymore
![AAA](https://github.com/p2or/blender-loom/assets/41523122/7fba2644-b915-4e10-86bd-9eb43c934d4d)
![BBB](https://github.com/p2or/blender-loom/assets/41523122/da065dc6-8ec3-4a7a-98d8-859d7b876d1f)

**Comment by p2or** [comment]
Hi @issimissimo,

same problem as last time. I would like to help, but I cannot reproduce your problem from the little information you have provided. All I can do is creating a trusty gif:

![ezgif-4-2eb99e29a3](https://github.com/p2or/blender-loom/assets/512368/43bea554-6fc5-4485-ad57-6720bc1ab205)

Even if the preview fails, are the paths and names after the _rendering_ at least as you would expect them to be? 

Cheers,
Christian

**Comment by issimissimo** [comment]
Sorry for my late reply! Indeed the frames are saved in the right folder. Openinf and closing the file does not change. I have idea that something happened when I've opened an "autosave" file created by the "Powersave" addon.
Anyway, it's working!
