### ISSUE TITLE
Only CPU rendering

### ISSUE THREAD

**Issue by hellooo94** [p2or/blender-loom#76]
It seems that Loom is only using the CPU to render, is this true? Any settings to use GPU?
Running latest Blender 4.0.2, Optix and RTX3080ti selected in the settings.

**Comment by p2or** [comment]
Hi @hellooo94,

What makes you think that? In general, _Loom_ only starts the actual job and there is no real connection to the settings of the render engine, which means that the scene is rendered as it is set. In fact, it's just a wrapper around the regular render operator (<kbd>F12</kbd>) to set the frame and the filepath.

Is there a difference for you when using <kbd>F12</kbd> vs. <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>F12</kbd> regarding _Optix_?

Cheers,
Christian

**Comment by p2or** [comment]
Closed due to inactivity. May reopen at any time, just let me know. Cheers @hellooo94
