### ISSUE TITLE
render specific keyframes operator Blender 2.90

### ISSUE THREAD

**Issue by Gattung** [p2or/blender-loom#8]
Hello and thanks for this great and useful tool.

In Blender 2.90 alpha the <kbd>Spacebar</kbd> or <kbd>F3</kbd> operator menu has changed and the *Render specific Keyframes* operator no longer works. 

Thanks for taking a look.

**Comment by p2or** [comment]
Hi @Gattung,

interesting catch, thanks. According to the [API changes of 2.90](https://wiki.blender.org/wiki/Reference/Release_Notes/2.90/Python_API) I added the operator to the render menu for now. Doesn't really make much sense at the first glance but we'll see whether that's a good thing, hopefully there is a good reason for that new limitation. 

![loom](https://user-images.githubusercontent.com/512368/80083510-fd809c00-8555-11ea-8307-fb43eee494d9.png)

Anyway, the operator should be available in the search menu <kbd>F3</kbd> again. If you have a better idea where to put it let me know and please test the updated version (0.5) and report back whether the patch works for you. 

Cheers,
Christian.

**Comment by Gattung** [comment]
Thanks Christian! 

Works great now!
 For me, the quickest way possible is best as I only render keyframes for storyboard animatics but I know I am a niche case.  If I could just make a quick menu item out of it that would be nice but not required.

Cheers,
Tom
