### ISSUE TITLE
An error rendering a linked scene

### ISSUE THREAD

**Issue by cbuhh** [p2or/blender-loom#93]
Blender 3.6 and 4.2
Create default scene with a cube.
New scene > Linked copy
For original scene: Loom > Render Image Sequence. Rendering occurs and completes without errors.
For duplicated scene:  Loom > Render Image Sequence
```
Python: Traceback (most recent call last):
  File "c:\blender\BlenderScripts\vanilla\addons\loom.py", line 1230, in execute
    if scn.render.use_sequencer and len(scn.sequence_editor.sequences):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sequences'
```

**Comment by p2or** [comment]
Hi @cbuhh,

thanks for your report! A similar issue already came up a few weeks ago in #88, but was not reproducible. Thanks to your simple example, it should be fixed as of the [latest commit](1b9be4ac2cffa65de389bdec5b1de60630100ef4). Can you confirm?

If you have the time, please clone or download Loom from the [master branch](https://github.com/p2or/blender-loom) and report back.

Cheers,
Christian
